from agents.code_agent import run_code_agent
from agents.test_agent import run_test_agent
from agents.security_agent import run_security_agent
from agents.docs_agent import run_docs_agent


def run_stagecraft_review(files):
    """
    Orchestrates the multi-agent review process.
    """
    results = []

    results.append(run_code_agent(files))
    results.append(run_test_agent(files))
    results.append(run_security_agent(files))
    results.append(run_docs_agent(files))

    return results


def build_report(results):
    """
    Aggregates results from multiple agents into a single markdown report.
    """
    report = "# 🚀 Stagecraft SDLC Review\n\n"
    report += "Our automated agents have analyzed your pull request. Here are the findings:\n\n"

    for r in results:
        report += f"### {r['agent']}\n"

        if not r["issues"]:
            report += "✔ No issues found\n\n"
        else:
            for issue in r["issues"]:
                report += f"- {issue}\n"
            report += "\n"

    report += "---\n*Generated by Stagecraft SDLC Agent Orchestrator*"
    return report
